### ISSUE TITLE
Be Exactly error? 

### ISSUE THREAD

**Issue by Ropiak** [EvotecIT/PesterInfrastructureTests#2]
Getting the error below. Looks like beExactly needs to be added as a function for Pester?

RuntimeException: '-BeExactly' is not a valid Should operator.
      at Get-TestResult, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Assertions\Should.ps1: line 42
      at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\PesterInfrastructureTests\0.0.2\Public\ActiveDirectory.ps1

**Comment by PrzemyslawKlys** [comment]
Install-module Pester -Force -SkipPublisherCheck

The built-in version in Windows is very old.

**Comment by Ropiak** [comment]
Worked thanks! I had to remove both modules then rerun the Pester this way.

**Comment by PrzemyslawKlys** [comment]
You could probably just do Install-Module PesterInfrastructureTests -Force which would do do nessecary reinstallation I believe
